// FIX: Moved all constants here from types.ts and added type imports.
import type { Property, Client, Campaign } from './types';

export const NAV_LINKS = [
    { name: 'nav.home', href: '#home' },
    { name: 'nav.properties', href: '#properties' },
    { name: 'nav.services', href: '#servicios' },
    { name: 'nav.about', href: '#about' },
    { name: 'nav.contact', href: '#contact' },
];

export const ACTIVITY_TYPES = [
    'Llamada al interesado',
    'Visita al interesado',
    'Enviar ficha del inmueble',
    'Mostrar inmueble',
    'Cotizar el inmueble',
    'Propuesta al dueño',
    'Ajuste de precio',
    'Documentación recibida',
    'Contrato firmado',
    'Otro',
];

export const PROPERTY_TYPES = [
    'Casa', 'Departamento', 'Terreno', 'Oficina', 'Local Comercial', 'Bodega Industrial', 'Loft', 'Villa', 'Hacienda'
];

export const AMENITIES_LIST = {
    Exterior: ['Acceso a la playa', 'Andén', 'Balcón', 'Cisterna', 'Estacionamiento techado', 'Facilidad para estacionarse', 'Frente a la playa', 'Frente al agua', 'Garaje', 'Jardín', 'Muelle de carga', 'Parrilla', 'Patio', 'Riego por aspersión', 'Roof garden', 'Terraza', 'Vista al agua', 'Vista al mar'],
    General: ['Accesibilidad para adultos mayores', 'Accesibilidad para personas con discapacidad', 'Aire acondicionado', 'Alarma', 'Amueblado', 'Bodega', 'Calefacción', 'Chimenea', 'Circuito cerrado', 'Cocina', 'Cocina equipada', 'Cocina integral', 'Conmutador', 'Cuarto de servicio', 'Dos plantas', 'Elevador', 'Estudio', 'Fraccionamiento privado', 'Hidroneumático', 'Oficina', 'Panel solar', 'Penthouse', 'Planta Baja', 'Planta eléctrica', 'Portero', 'Rampas', 'Recámara en planta baja', 'Seguridad 12 horas', 'Seguridad 24 horas', 'Una sola planta'],
    Políticas: ['Mascotas permitidas', 'No se aceptan mascotas', 'Permitido fumar', 'Prohibido fumar'],
    Recreación: ['Alberca', 'Área de juegos infantiles', 'Cancha de pádel', 'Cancha de tenis', 'Cine', 'Fogatero', 'Gimnasio', 'Jacuzzi', 'Ludoteca', 'Salón de usos múltiples', 'Sauna']
};

export const SAMPLE_CLIENTS: Client[] = [
    {
        id: 'client-1',
        name: 'Carlos Hernández',
        email: 'carlos.h@example.com',
        phone: '55-1234-5678',
        status: 'Activo',
        leadSource: 'Web',
        assignedAgentId: 'agent1',
        notes: 'Interesado en propiedades en Polanco. Busca 3 recámaras.',
        activityLog: [],
        createdAt: new Date('2023-10-15T10:00:00Z').toISOString(),
    },
    {
        id: 'client-2',
        name: 'Ana García',
        email: 'ana.g@example.com',
        phone: '33-9876-5432',
        status: 'Lead',
        leadSource: 'Referido',
        notes: 'Primer contacto. Referida por un cliente anterior. Busca invertir en terrenos.',
        activityLog: [],
        createdAt: new Date('2023-11-05T14:30:00Z').toISOString(),
    },
    {
        id: 'client-3',
        name: 'Sofía Martínez',
        email: 'sofia.m@example.com',
        status: 'Contactado',
        assignedAgentId: 'agent2',
        notes: 'Se le envió información sobre la villa en Cancún.',
        activityLog: [],
        createdAt: new Date('2024-01-20T09:00:00Z').toISOString(),
    }
];

export const SAMPLE_PROPERTIES: Property[] = [
    {
        id: 'prop-1',
        title: 'Villa de Lujo con Vista al Mar',
        description: 'Espectacular villa de lujo con acabados de primera y una inigualable vista al mar Caribe. Ideal para quienes buscan exclusividad y confort.',
        location: 'Cancún, Quintana Roo',
        price: 25000000,
        bedrooms: 5,
        bathrooms: 6,
        halfBathrooms: 1,
        parkingSpaces: 4,
        constructionArea: 800,
        landArea: 1200,
        type: 'Villa',
        images: ['https://picsum.photos/id/1018/600/400', 'https://picsum.photos/id/1015/600/400', 'https://picsum.photos/id/1016/600/400'],
        amenities: ['Alberca', 'Jardín', 'Vista al mar', 'Gimnasio', 'Seguridad 24 horas', 'Terraza', 'Estacionamiento techado'],
        latitude: 21.1619,
        longitude: -86.8515,
        status: 'For Sale',
        operationType: 'Venta',
        showPrice: true,
        constructionYear: 2022,
        activityLog: [],
        country: 'México',
        state: 'Quintana Roo',
        city: 'Cancún',
        street: 'Av. Kukulcan',
        agentId: 'agent2',
        clientId: 'client-3',
        pipelineStage: 'Negociación',
    },
    {
        id: 'prop-2',
        title: 'Moderno Departamento en Polanco',
        description: 'Ubicado en el corazón de Polanco, este departamento combina diseño moderno, comodidad y acceso a las mejores zonas de la ciudad.',
        location: 'Polanco, Ciudad de México',
        price: 12500000,
        bedrooms: 3,
        bathrooms: 3,
        halfBathrooms: 1,
        parkingSpaces: 2,
        constructionArea: 250,
        type: 'Departamento',
        images: ['https://picsum.photos/id/1025/600/400', 'https://picsum.photos/id/1026/600/400', 'https://picsum.photos/id/1028/600/400'],
        amenities: ['Roof garden', 'Gimnasio', 'Salón de usos múltiples', 'Elevador', 'Seguridad 24 horas'],
        latitude: 19.4326,
        longitude: -99.1332,
        status: 'For Sale',
        operationType: 'Venta',
        showPrice: true,
        floorNumber: 10,
        buildingFloors: 15,
        activityLog: [],
        country: 'México',
        state: 'Ciudad de México',
        city: 'Ciudad de México',
        street: 'Av. Presidente Masaryk',
        clientId: 'client-1',
        agentId: 'agent1',
        pipelineStage: 'Visita Agendada',
    },
    {
        id: 'prop-3',
        title: 'Casa Familiar en Querétaro',
        description: 'Amplia casa familiar en uno de los fraccionamientos más exclusivos de Querétaro. Perfecta para una vida tranquila y segura.',
        location: 'Juriquilla, Querétaro',
        price: 6800000,
        bedrooms: 4,
        bathrooms: 4,
        parkingSpaces: 3,
        constructionArea: 450,
        landArea: 500,
        type: 'Casa',
        images: ['https://picsum.photos/id/1040/600/400', 'https://picsum.photos/id/1041/600/400'],
        amenities: ['Jardín', 'Cuarto de servicio', 'Terraza', 'Fraccionamiento privado', 'Seguridad 24 horas'],
        latitude: 20.5888,
        longitude: -100.3899,
        status: 'Sold',
        agentId: 'agent1',
        operationType: 'Venta',
        showPrice: true,
        activityLog: [],
        country: 'México',
        state: 'Querétaro',
        city: 'Querétaro',
        street: 'Paseo de la República',
        pipelineStage: 'Cerrado',
        soldAt: new Date('2023-12-01T18:00:00Z').toISOString(),
        commissionAmount: 170000, // 6,800,000 * 2.5%
    },
    {
        id: 'prop-4',
        title: 'Loft Industrial en la Roma',
        description: 'Loft con un diseño industrial único, techos altos y espacios abiertos. Ideal para creativos y amantes del estilo urbano.',
        location: 'Roma Norte, Ciudad de México',
        price: 8900000,
        bedrooms: 2,
        bathrooms: 2,
        parkingSpaces: 1,
        constructionArea: 180,
        type: 'Loft',
        images: ['https://picsum.photos/id/1060/600/400', 'https://picsum.photos/id/1062/600/400'],
        amenities: ['Balcón', 'Elevador', 'Seguridad 24 horas'],
        latitude: 19.419,
        longitude: -99.163,
        status: 'For Sale',
        agentId: 'agent2',
        operationType: 'Venta',
        showPrice: true,
        activityLog: [],
        country: 'México',
        state: 'Ciudad de México',
        city: 'Ciudad de México',
        street: 'Orizaba',
        pipelineStage: 'Contactado',
    },
    {
        id: 'prop-5',
        title: 'Terreno Residencial en Valle de Bravo',
        description: 'Oportunidad única para construir la casa de tus sueños en Valle de Bravo, con vistas espectaculares al lago y en una zona de alta plusvalía.',
        location: 'Valle de Bravo, Estado de México',
        price: 4500000,
        bedrooms: 0,
        bathrooms: 0,
        // FIX: Added missing 'parkingSpaces' property.
        parkingSpaces: 0,
        constructionArea: 0,
        landArea: 1000,
        type: 'Terreno',
        images: ['https://picsum.photos/id/1084/600/400'],
        amenities: ['Vista al agua', 'Fraccionamiento privado'],
        latitude: 19.1910,
        longitude: -100.1319,
        status: 'For Sale',
        operationType: 'Venta',
        showPrice: true,
        activityLog: [],
        country: 'México',
        state: 'Estado de México',
        city: 'Valle de Bravo',
        street: 'Camino a la Peña',
        clientId: 'client-2',
        pipelineStage: 'Lead',
    },
    {
        id: 'prop-6',
        title: 'Hacienda Histórica Restaurada',
        description: 'Majestuosa hacienda henequenera restaurada, que combina el encanto histórico con las comodidades modernas. Un tesoro en el corazón de Yucatán.',
        location: 'Mérida, Yucatán',
        price: 45000000,
        bedrooms: 8,
        bathrooms: 9,
        parkingSpaces: 10,
        constructionArea: 2500,
        landArea: 10000,
        type: 'Hacienda',
        images: ['https://picsum.photos/id/211/600/400', 'https://picsum.photos/id/212/600/400'],
        amenities: ['Alberca', 'Jardín', 'Capilla', 'Terraza'],
        latitude: 20.9674,
        longitude: -89.5926,
        status: 'For Sale',
        agentId: 'agent2',
        operationType: 'Venta',
        showPrice: true,
        activityLog: [],
        country: 'México',
        state: 'Yucatán',
        city: 'Mérida',
        street: 'Carretera a Chichén Itzá',
        pipelineStage: 'Lead',
    },
];

export const SAMPLE_CAMPAIGNS: Campaign[] = [
    {
        id: 'campaign-1',
        name: 'Lanzamiento Nuevas Propiedades Polanco',
        subject: '¡Exclusivo! Nuevas propiedades de lujo en Polanco',
        body: 'Hola {{client_name}},\n\nNo te pierdas la oportunidad de conocer nuestras nuevas propiedades en la zona más exclusiva de la Ciudad de México. ¡Agenda una visita hoy mismo!',
        targetAudience: {
            status: ['Activo', 'Lead'],
            leadSource: ['Web', 'Referido']
        },
        status: 'Borrador',
        sentToCount: 0,
    },
    {
        id: 'campaign-2',
        name: 'Promoción Terrenos de Inversión',
        subject: 'Invierte en tu futuro: Terrenos con alta plusvalía',
        body: 'Estimado/a {{client_name}},\n\nDescubre las mejores oportunidades para invertir en terrenos en zonas de alto crecimiento. ¡Contáctanos para más información!',
        targetAudience: {
            status: ['Lead'],
            leadSource: []
        },
        status: 'Enviada',
        sentAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(), // 1 week ago
        sentToCount: 1,
    }
];


export const PRICE_RANGE = {
    min: 500000,
    max: 50000000,
};